### ISSUE TITLE
The Copy URL icon from the Share menu should be white

### ISSUE THREAD

**Issue by jvendrell** [vilanovailageltru/decidim-vilanova#23]
The icon of the Copy URL button of the Share menu is black but should be white.

<img width="689" alt="screen shot 2017-03-21 at 10 38 28" src="https://cloud.githubusercontent.com/assets/7082300/24141120/ba4930ee-0e22-11e7-91c3-95c7788b0ad2.png">

**Comment by xredo** [comment]
This is not an error of this Decidim installation. It is displayed this way in all Decidim installs.
