### ISSUE TITLE
Transfer Github repository

### ISSUE THREAD

**Issue by xredo** [vilanovailageltru/decidim-vilanova#6]
Once the Vilanova repository is created we will transfer it from the MarsBased organitzation to the Vilanova one.

**Comment by andreslucena** [comment]
I think it's better that you guys just create the Github organization and then give Owner to one of the Vilanova's IT people (at least that's how we did it on BCN and others city halls), except if they already had one (sadly, this isn't usually the case).

**Comment by xredo** [comment]
Hi @andreslucena, thank you for your feedback. They already have their own Github Organization and we have agreed with their IT people to transfer the repository to them during the technical training.
